### ISSUE TITLE
Any plans?

### ISSUE THREAD

**Issue by garrettw** [Viper-7/electrobot#1]
Hey, I just saw that you created this repo, and from the looks of it this must be some old code you wrote for an IRC bot framework that you just decided to put on GitHub.

I noticed that this repo’s name differs from the lib name your code mentions (V7IRCFramework I think it was). Are you planning on a major refactor/reboot starting from the old code?

**Comment by Viper-7** [comment]
No major plans, the V7IRCFramework lib has been in github for a long time, but not as its own project, rather as part of my Snippets repository. I wrote it as a lightweight basis for IRC bots without the configuration and guff required by regular bot engines, and with a bit more flexibility. I use it for basic tasks like health monitoring services, through to purpose specific jobs like a trivia bot or the electronics bot this repository is for.

I never really wrote it to become a popular library used by others, but if you're interested i'm happy to make a canonical repository for it, although I don't see myself making any great changes to it at this point.

**Comment by garrettw** [comment]
Ah, ok. I had started developing my own IRC lib a while back but never finished it – so if you were going to develop it, I was going to watch it and maybe use it or contribute to it. But if not, that’s fine too; I don’t actually have a pressing need for an IRC bot at the moment anyway.
